name: Hello World
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Steps
        run: | 
          echo "Welcome To the Git Hub Actions"
          echo "How's Your learning going on"
